### ISSUE TITLE
Cards nella pagina dei seminari della stessa dimensione "statica"

### ISSUE THREAD

**Issue by carcaru** [LaboratorioSperimentale/seminari#10]
https://github.com/LaboratorioSperimentale/seminari/blob/d5528c9481f2c731bcd0739a774be38d56734dee/_includes/card.html#L1

forse in _styles cards.css

utilizzare:

```css


.container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: stretch; /* Ensures all cards match the tallest one */
}

.card {
  display: flex;
  flex-direction: column;
  width: 350px;
  max-width: calc(100% - 40px);
  margin: 20px;
  background: var(--background);
  border-radius: var(--rounded);
  overflow: hidden;
  box-shadow: var(--shadow);
  vertical-align: top;
  flex: 1; /* Allows cards to expand to match the tallest one */
}

```

**Comment by carcaru** [comment]
questo è il codice originale


```css

.card {
  display: inline-flex;
  justify-content: stretch;
  align-items: center;
  flex-direction: column;
  width: 350px;
  max-width: calc(100% - 20px - 20px);
  margin: 20px;
  background: var(--background);
  border-radius: var(--rounded);
  overflow: hidden;
  box-shadow: var(--shadow);
  vertical-align: top;
}
```
